// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)
FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, csrf_token, ip_address, user_agent, expires_at,
       absolute_expires_at, last_seen_at, revoked_at, created_at
FROM sessions
WHERE token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	CsrfToken         string             `json:"csrf_token"`
	IpAddress         string             `json:"ip_address"`
	UserAgent         string             `json:"user_agent"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfToken,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, nickname, alias, campus_identity, role, status,
       credit, xp, avatar_path, dm_stranger_off, hide_online, verified_at, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             int64              `json:"id"`
	Email          pgtype.Text        `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	Nickname       string             `json:"nickname"`
	Alias          string             `json:"alias"`
	CampusIdentity string             `json:"campus_identity"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	Credit         int32              `json:"credit"`
	Xp             int32              `json:"xp"`
	AvatarPath     pgtype.Text        `json:"avatar_path"`
	DmStrangerOff  bool               `json:"dm_stranger_off"`
	HideOnline     bool               `json:"hide_online"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Nickname,
		&i.Alias,
		&i.CampusIdentity,
		&i.Role,
		&i.Status,
		&i.Credit,
		&i.Xp,
		&i.AvatarPath,
		&i.DmStrangerOff,
		&i.HideOnline,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
