// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	EntityID int64              `json:"entity_id"`
	Category string             `json:"category"`
	Title    string             `json:"title"`
	Body     string             `json:"body"`
	Location string             `json:"location"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
	Capacity pgtype.Int4        `json:"capacity"`
	Status   string             `json:"status"`
}

type ActivityMember struct {
	ID         int64              `json:"id"`
	ActivityID int64              `json:"activity_id"`
	UserID     int64              `json:"user_id"`
	Status     string             `json:"status"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
}

type Announcement struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	Level       string             `json:"level"`
	Audience    string             `json:"audience"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type AnnouncementRead struct {
	ID             int64              `json:"id"`
	AnnouncementID int64              `json:"announcement_id"`
	UserID         int64              `json:"user_id"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

type Answer struct {
	EntityID   int64  `json:"entity_id"`
	QuestionID int64  `json:"question_id"`
	Body       string `json:"body"`
}

type Appeal struct {
	ID        int64              `json:"id"`
	PenaltyID int64              `json:"penalty_id"`
	UserID    int64              `json:"user_id"`
	Reason    string             `json:"reason"`
	Status    string             `json:"status"`
	AdminNote string             `json:"admin_note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Attachment struct {
	ID            int64              `json:"id"`
	OwnerID       int64              `json:"owner_id"`
	EntityID      pgtype.Int8        `json:"entity_id"`
	Path          string             `json:"path"`
	ThumbnailPath string             `json:"thumbnail_path"`
	StorageBucket string             `json:"storage_bucket"`
	AccessScope   string             `json:"access_scope"`
	MimeType      string             `json:"mime_type"`
	SizeBytes     int32              `json:"size_bytes"`
	Width         int32              `json:"width"`
	Height        int32              `json:"height"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	ActorID    pgtype.Int8        `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	Reason     string             `json:"reason"`
	BeforeJson string             `json:"before_json"`
	AfterJson  string             `json:"after_json"`
	RequestID  string             `json:"request_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BackupJob struct {
	ID            int64              `json:"id"`
	RequestedBy   int64              `json:"requested_by"`
	Status        string             `json:"status"`
	FilePath      string             `json:"file_path"`
	DownloadToken string             `json:"download_token"`
	Error         string             `json:"error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

type Block struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	BlockedID int64              `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CampusService struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Category      string             `json:"category"`
	ManagerUserID pgtype.Int8        `json:"manager_user_id"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CampusServiceRating struct {
	ID          int64              `json:"id"`
	ServiceID   int64              `json:"service_id"`
	UserID      int64              `json:"user_id"`
	Rating      int32              `json:"rating"`
	Body        string             `json:"body"`
	Response    string             `json:"response"`
	ResponderID pgtype.Int8        `json:"responder_id"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Comment struct {
	EntityID       int64       `json:"entity_id"`
	TargetEntityID int64       `json:"target_entity_id"`
	ParentID       pgtype.Int8 `json:"parent_id"`
	ReplyToUserID  pgtype.Int8 `json:"reply_to_user_id"`
	Body           string      `json:"body"`
	IdentityMode   string      `json:"identity_mode"`
}

type ContentEntity struct {
	ID                int64              `json:"id"`
	Type              string             `json:"type"`
	OwnerID           int64              `json:"owner_id"`
	PublicationStatus string             `json:"publication_status"`
	ModerationStatus  string             `json:"moderation_status"`
	AllowComments     bool               `json:"allow_comments"`
	SearchVisible     bool               `json:"search_visible"`
	ModerationReason  string             `json:"moderation_reason"`
	Revision          int32              `json:"revision"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ContentRevision struct {
	ID        int64              `json:"id"`
	EntityID  int64              `json:"entity_id"`
	EditorID  int64              `json:"editor_id"`
	Revision  int32              `json:"revision"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID          int64              `json:"id"`
	ContextType string             `json:"context_type"`
	ContextID   pgtype.Int8        `json:"context_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ConversationMember struct {
	ID             int64              `json:"id"`
	ConversationID int64              `json:"conversation_id"`
	UserID         int64              `json:"user_id"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
}

type Course struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Teacher string `json:"teacher"`
	Active  bool   `json:"active"`
}

type CourseOffering struct {
	ID       int64  `json:"id"`
	CourseID int64  `json:"course_id"`
	Semester string `json:"semester"`
	Section  string `json:"section"`
}

type CourseReview struct {
	EntityID   int64  `json:"entity_id"`
	OfferingID int64  `json:"offering_id"`
	UserID     int64  `json:"user_id"`
	Rating     int32  `json:"rating"`
	Tags       string `json:"tags"`
	Body       string `json:"body"`
	Correction string `json:"correction"`
}

type CreditRule struct {
	Key         string             `json:"key"`
	Label       string             `json:"label"`
	Kind        string             `json:"kind"`
	Value       int32              `json:"value"`
	Description string             `json:"description"`
	UpdatedBy   pgtype.Int8        `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EmailOutbox struct {
	ID            int64              `json:"id"`
	ToEmail       string             `json:"to_email"`
	Subject       string             `json:"subject"`
	Body          string             `json:"body"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	LastError     string             `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Favorite struct {
	ID        int64              `json:"id"`
	EntityID  int64              `json:"entity_id"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Feedback struct {
	EntityID  int64  `json:"entity_id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Status    string `json:"status"`
	AdminNote string `json:"admin_note"`
}

type GameSubmission struct {
	ID             int64              `json:"id"`
	SubmitterID    int64              `json:"submitter_id"`
	ProposedName   string             `json:"proposed_name"`
	Aliases        []byte             `json:"aliases"`
	Status         string             `json:"status"`
	ResolvedGameID pgtype.Int8        `json:"resolved_game_id"`
	ReviewerID     pgtype.Int8        `json:"reviewer_id"`
	AdminNote      string             `json:"admin_note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
}

type HandbookArticle struct {
	EntityID         int64              `json:"entity_id"`
	Category         string             `json:"category"`
	Title            string             `json:"title"`
	Body             string             `json:"body"`
	FeaturedAt       pgtype.Timestamptz `json:"featured_at"`
	FeaturedRewarded bool               `json:"featured_rewarded"`
}

type Listing struct {
	EntityID    int64       `json:"entity_id"`
	CategoryID  int64       `json:"category_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	PriceCents  int64       `json:"price_cents"`
	Condition   string      `json:"condition"`
	Negotiable  bool        `json:"negotiable"`
	PurchasedAt pgtype.Date `json:"purchased_at"`
	LocationID  int64       `json:"location_id"`
	TradeStatus string      `json:"trade_status"`
}

type LostClaim struct {
	ID         int64              `json:"id"`
	ItemID     int64              `json:"item_id"`
	ClaimantID int64              `json:"claimant_id"`
	Message    string             `json:"message"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DecidedAt  pgtype.Timestamptz `json:"decided_at"`
}

type LostItem struct {
	EntityID    int64              `json:"entity_id"`
	Kind        string             `json:"kind"`
	ItemName    string             `json:"item_name"`
	Description string             `json:"description"`
	Location    string             `json:"location"`
	HappenedAt  pgtype.Timestamptz `json:"happened_at"`
	Status      string             `json:"status"`
}

type MarketCategory struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Active    bool               `json:"active"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MarketDispute struct {
	ID            int64              `json:"id"`
	TransactionID int64              `json:"transaction_id"`
	OpenedBy      int64              `json:"opened_by"`
	Reason        string             `json:"reason"`
	Status        string             `json:"status"`
	Decision      string             `json:"decision"`
	AdminNote     string             `json:"admin_note"`
	DecidedBy     pgtype.Int8        `json:"decided_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
}

type MarketDisputeEvidence struct {
	DisputeID    int64 `json:"dispute_id"`
	AttachmentID int64 `json:"attachment_id"`
}

type MarketLocation struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Active    bool               `json:"active"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MarketReview struct {
	ID            int64              `json:"id"`
	TransactionID int64              `json:"transaction_id"`
	ReviewerID    int64              `json:"reviewer_id"`
	RevieweeID    int64              `json:"reviewee_id"`
	Rating        int32              `json:"rating"`
	Body          string             `json:"body"`
	VisibleAt     pgtype.Timestamptz `json:"visible_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type MarketTransaction struct {
	ID                int64              `json:"id"`
	ListingID         int64              `json:"listing_id"`
	SellerID          int64              `json:"seller_id"`
	BuyerID           int64              `json:"buyer_id"`
	Status            string             `json:"status"`
	Message           string             `json:"message"`
	ReservedUntil     pgtype.Timestamptz `json:"reserved_until"`
	BuyerConfirmedAt  pgtype.Timestamptz `json:"buyer_confirmed_at"`
	SellerConfirmedAt pgtype.Timestamptz `json:"seller_confirmed_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy       pgtype.Int8        `json:"cancelled_by"`
	CancelReason      string             `json:"cancel_reason"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	EntityID       int64  `json:"entity_id"`
	ConversationID int64  `json:"conversation_id"`
	Body           string `json:"body"`
}

type ModerationCase struct {
	ID         int64              `json:"id"`
	EntityID   int64              `json:"entity_id"`
	Source     string             `json:"source"`
	Status     string             `json:"status"`
	AssigneeID pgtype.Int8        `json:"assignee_id"`
	Decision   string             `json:"decision"`
	Notes      string             `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DecidedAt  pgtype.Timestamptz `json:"decided_at"`
}

type Notification struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Link      string             `json:"link"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ObservePost struct {
	EntityID     int64              `json:"entity_id"`
	Title        string             `json:"title"`
	BodyMasked   string             `json:"body_masked"`
	BodyRaw      string             `json:"body_raw"`
	RespondentID pgtype.Int8        `json:"respondent_id"`
	Response     string             `json:"response"`
	ResponseAt   pgtype.Timestamptz `json:"response_at"`
	AdminNote    string             `json:"admin_note"`
}

type Penalty struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	PublicMask    string             `json:"public_mask"`
	ViolationType string             `json:"violation_type"`
	Result        string             `json:"result"`
	Rule          string             `json:"rule"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	EntityID     int64              `json:"entity_id"`
	Board        string             `json:"board"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	IdentityMode string             `json:"identity_mode"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Views        int32              `json:"views"`
}

type Question struct {
	EntityID         int64       `json:"entity_id"`
	Title            string      `json:"title"`
	Body             string      `json:"body"`
	Category         string      `json:"category"`
	Tags             string      `json:"tags"`
	BountyXp         int32       `json:"bounty_xp"`
	BountySettled    bool        `json:"bounty_settled"`
	AcceptedAnswerID pgtype.Int8 `json:"accepted_answer_id"`
}

type RateLimitCounter struct {
	Action      string             `json:"action"`
	Subject     string             `json:"subject"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	Count       int32              `json:"count"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type Reaction struct {
	ID        int64              `json:"id"`
	EntityID  int64              `json:"entity_id"`
	UserID    int64              `json:"user_id"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID         int64              `json:"id"`
	EntityID   int64              `json:"entity_id"`
	ReporterID int64              `json:"reporter_id"`
	Reason     string             `json:"reason"`
	Detail     string             `json:"detail"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	CsrfToken         string             `json:"csrf_token"`
	IpAddress         string             `json:"ip_address"`
	UserAgent         string             `json:"user_agent"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `json:"absolute_expires_at"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedBy pgtype.Int8        `json:"updated_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	EntityID                      int64       `json:"entity_id"`
	OwnerID                       int64       `json:"owner_id"`
	GameID                        pgtype.Int8 `json:"game_id"`
	Game                          string      `json:"game"`
	Mode                          string      `json:"mode"`
	RankRequirement               string      `json:"rank_requirement"`
	Capacity                      int32       `json:"capacity"`
	VoiceName                     string      `json:"voice_name"`
	VoiceLink                     string      `json:"voice_link"`
	Notes                         string      `json:"notes"`
	NewbieLevel                   string      `json:"newbie_level"`
	Vibe                          string      `json:"vibe"`
	ReminderChannels              string      `json:"reminder_channels"`
	Recurrence                    string      `json:"recurrence"`
	ReminderMinutes               int32       `json:"reminder_minutes"`
	PostDepartureRetentionMinutes int32       `json:"post_departure_retention_minutes"`
	Status                        string      `json:"status"`
}

type TeamGame struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TeamGameAlias struct {
	ID              int64  `json:"id"`
	GameID          int64  `json:"game_id"`
	Alias           string `json:"alias"`
	NormalizedAlias string `json:"normalized_alias"`
}

type TeamMembership struct {
	ID               int64              `json:"id"`
	TeamID           int64              `json:"team_id"`
	UserID           int64              `json:"user_id"`
	Role             string             `json:"role"`
	Status           string             `json:"status"`
	ReminderChannels string             `json:"reminder_channels"`
	JoinedAt         pgtype.Timestamptz `json:"joined_at"`
	LeftAt           pgtype.Timestamptz `json:"left_at"`
}

type TeamRating struct {
	ID        int64              `json:"id"`
	RunID     int64              `json:"run_id"`
	RaterID   int64              `json:"rater_id"`
	TargetID  int64              `json:"target_id"`
	Tag       string             `json:"tag"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TeamRun struct {
	ID             int64              `json:"id"`
	TeamID         int64              `json:"team_id"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	Status         string             `json:"status"`
	ReminderSentAt pgtype.Timestamptz `json:"reminder_sent_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type TeamRunMember struct {
	ID            int64              `json:"id"`
	RunID         int64              `json:"run_id"`
	UserID        int64              `json:"user_id"`
	Status        string             `json:"status"`
	CheckedInAt   pgtype.Timestamptz `json:"checked_in_at"`
	ExcusedAt     pgtype.Timestamptz `json:"excused_at"`
	CreditAwarded bool               `json:"credit_awarded"`
}

type ThreadAnonymousIdentity struct {
	ID          int64              `json:"id"`
	ThreadID    int64              `json:"thread_id"`
	UserID      int64              `json:"user_id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             int64              `json:"id"`
	Email          pgtype.Text        `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	Nickname       string             `json:"nickname"`
	Alias          string             `json:"alias"`
	CampusIdentity string             `json:"campus_identity"`
	Role           string             `json:"role"`
	Status         string             `json:"status"`
	Credit         int32              `json:"credit"`
	Xp             int32              `json:"xp"`
	AvatarPath     pgtype.Text        `json:"avatar_path"`
	DmStrangerOff  bool               `json:"dm_stranger_off"`
	HideOnline     bool               `json:"hide_online"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	DeactivatedAt  pgtype.Timestamptz `json:"deactivated_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type VerificationCode struct {
	ID         int64              `json:"id"`
	Email      string             `json:"email"`
	Purpose    string             `json:"purpose"`
	CodeHash   string             `json:"code_hash"`
	IpAddress  string             `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type WorkerHeartbeat struct {
	WorkerName    string             `json:"worker_name"`
	InstanceID    string             `json:"instance_id"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	LastError     string             `json:"last_error"`
}
