// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUnreadNotifications(ctx context.Context, userID int64) (int64, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (GetUserByEmailRow, error)
}

var _ Querier = (*Queries)(nil)
